### ISSUE TITLE
Betweenlands has too many problems with shaders mod

### ISSUE THREAD

**Issue by lightning02** [Angry-Pixel/The-Betweenlands#299] opened 2016-05-24 12:55 UTC
Hello, first of all let me congratulate with you all for the hard work done with this mod, the 3d models are great and all the stuff too.
Anyway, I think that every mod being developed has to consider compatibility with 3 focal points, Optifine, Fastcraft and ShaderMod.
The last one in this case wasn't well fitting with betweenland, or maybe are the shader packs from different authors, by the way, thebetweenlad kinda breaks almost every shader pack, plus, the game doesn't even initialize if you don't disable;
"    B:"Use shaders for rendering (this forces FBOs to be enabled)"=false" 
in the betweenland config.
giving this error
http://pastebin.com/tDuaP0K3
And this one is part of the log with that option disabled;
http://pastebin.com/f3DcXQcT

Finally, these are the results with different shader packs tried:

Chocapic13 V5 Extreme
![1](https://cloud.githubusercontent.com/assets/11884147/15504130/c3266878-21bd-11e6-83e6-9a4a368a5c1f.png)

Kuda-Shaders v5.0.4 Ultra
![2](https://cloud.githubusercontent.com/assets/11884147/15504197/0fc2334c-21be-11e6-88d2-9af2ad5677e8.png)

Silidurs Vibrant Shaders v1.0.8 Extreme
![3](https://cloud.githubusercontent.com/assets/11884147/15504263/70507570-21be-11e6-9a95-72e1d49ba652.png)

SEUS v10-0 Ultra No Blur
![4](https://cloud.githubusercontent.com/assets/11884147/15504284/8c5cea5a-21be-11e6-8f93-21b53f8584cd.png)

SEUS v10.1 Ultra Motion Blur
![5](https://cloud.githubusercontent.com/assets/11884147/15504305/a7c0aeee-21be-11e6-9219-9dcdf5f4167e.png)

The only that seems to be decent is seus motion blur, even if there is too much light saturation in the evniroment, and in the end, this happen when you go underwater...
![6](https://cloud.githubusercontent.com/assets/11884147/15504361/e1e33150-21be-11e6-87d1-f1132f6eb7b2.png)

Could be at least be done some config option to make beetweenland don't use any shader at all?

**Comment by TheCyberBrick** [comment] 2016-05-24 13:55
1. OptiFine is compatible, you simply have to set "Fast Render" to OFF because it disables the vanilla (!) shader system the BL is using. Optifine shows a warning saying that Fast Render disables shaders.

2. Is there a problem with Fastcraft? We've used it before and it seemed to work fine.

3. Incompatibility with shaders mod is already fixed in the dev version

4. "Could be at least be done some config option to make beetweenland don't use any shader at all?"
Yes, there is. If you disable them in the config file they are totally disabled. The shaders mod incompatibilities weren't caused by the BL shaders in the first place anyways.

You should probably wait for the next update and then try again :)

**Closed** 2016-05-24 13:56 UTC

**Comment by lightning02** [comment] 2016-05-24 15:27
I think I've disabled the shaders from BL in the config in:
#  [default: true]
    B:"Use shaders for rendering (this forces FBOs to be enabled)"=false

That's why I was asking.. I also noticed that when I totally removed the mod (Betweenland) everything from Shader Mod was working fine.
Maybe is something with other BL rendering settings that may cause the issue?

Also, I've removed fastcraft and optifine (since I've cited them but only sayng they are important, not they are related with the issue), in fact, removing them the problem remain the same..

![a5542195e796e6622ad412693c83e4bf86a2611ff1154104b2 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11884147/15509579/43d8987c-21d4-11e6-8dc5-93bc0e01a648.png)


Removing BL every shader pack works fine.

**Comment by TheCyberBrick** [comment] 2016-05-24 17:16
Yes, that's what I said: "The shaders mod incompatibilities weren't caused by the BL shaders in the first place anyways."
It was some overlay rendering that caused these issues.
Anyways, this is already fixed in the dev version which is why I closed the issue.

**Comment by lightning02** [comment] 2016-05-24 17:40
Oh, well, sorry, maybe I misunderstood something, my english is not so good at all :l
By the way, how much time we have to wait (more or less) for the next release? Just to get an idea, I want not bother

**Comment by TheCyberBrick** [comment] 2016-05-24 18:14
Don't worry, you didn't bother anyone :P
Not quite sure about the next update yet. I guess we could release one soon with the fixes only and then later on release a content update again.

**Comment by lightning02** [comment] 2016-05-24 20:34
This would be amazing, I badly need that update :c

**Comment by lightning02** [comment] 2016-05-30 14:07
Are there any news about the update?

**Comment by TheCyberBrick** [comment] 2016-06-12 19:37
@lightning02 The update is now available
