### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by Darkosto** [Angry-Pixel/The-Betweenlands#309] opened 2016-06-13 06:17 UTC
Hello! 

I was testing out the betweenlands today and came across this crash: 

http://pastebin.com/URRuU5a1

It first started when looking through NEI, which I think may have caused it? I reloaded the pack to be instantly crashed out with the crash report I posted.

Thanks for taking a look!
Darkosto

**Comment by TheCyberBrick** [comment] 2016-06-13 07:54
Did you spawn in the Guide Book? It can't be obtained normally because it's not finished yet and in the crash log it looks like it's caused by the Guide Book.

**Comment by vadis365** [comment] 2016-06-13 10:27
Our best minds are working on it... :P

**Comment by Darkosto** [comment] 2016-06-13 18:41
Seems like they have you, Vadis! That's the best a team could ask for! :)

Yup, CyberBrick, I had the guide book in my inventory. I was doing some exploring and was checking the book out. I'll make sure not to do that again!

Thanks for the help and the mod is looking amazing!

**Comment by vadis365** [comment] 2016-06-13 18:44
We think it should be a simple enough fix - but not sure when it will be done.
Let us know if/when you stream any BL stuff and I'll see if I can get some of the team to pop on to say hello :)

**Comment by Darkosto** [comment] 2016-06-13 21:16
I do have one question, is there an in-game guide for players to learn how to get to the betweenlands? I hate sending players out of the game to find out.

**Comment by MrCompost** [comment] 2016-06-13 22:12
There's just one for Herblore currently. We did quite some work on a general BL one but things got kinda messy so it'll have to be revisited sometime, probably after 1.9.

**Comment by TheCyberBrick** [comment] 2016-08-19 14:58
This will be fixed once the HL book is properly implemented

**Closed by TheCyberBrick** 2016-08-19 14:58 UTC
Labels: 1.7
